# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
